name: CICD

on:
  push:
    branches: [ main, 'release-*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMG_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com

    steps:
    - name: Set up env
      run: |
        if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
          echo "IMG_TAG=latest" >> "$GITHUB_ENV"
        else
          echo "IMG_TAG=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
        fi

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Login to the container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: make docker-build
      env:
        IMG_TAG: ${{ env.IMG_TAG }}

    - name: Push
      if: ${{ github.event_name != 'pull_request' }}
      run: make docker-push
      env:
        IMG_TAG: ${{ env.IMG_TAG }}
